version: '3.2'

services:
  websphere:
    image: ibmcom/websphere-traditional:${WEBSPHERE_VERSION-9.0.5.14}
    volumes:
      - $PWD/console-password:/tmp/PASSWORD
    ports:
      - 9043:9043
      - 9080:9080
      - 9443:9443
    restart: always
    networks:
      - websphere

networks:
  websphere:
    driver: bridge
