version: '3.2'

services:
  mongodb:
    image: mongo:${MONGO_VERSION-5.0}
    volumes:
      - mongodbdata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_PASSWORD-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD-password}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME-database}
    ports:
      - 27017-27019:27017-27019
    restart: unless-stopped
    networks:
      - databases

volumes:
  mongodbdata:
    driver: local

networks:
  databases:
    driver: bridge