version: '3.2'

services:
  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION-latest}
    volumes:
      - $PWD/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - $PWD/config/alert.rules.yml://etc/prometheus/alert.rules.yml
      - prometheusdata:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.route-prefix=/'
      - '--storage.tsdb.retention.time=${PROMETHEUS_RETENTION-30d}'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    restart: unless-stopped
    networks:
      - prometheus

  alertmanager:
    image: prom/alertmanager:${ALERTMANAGER_VERSION-latest}
    volumes:
      - $PWD/config/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    ports:
      - 9091:9091
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - prometheus

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION-latest}
    environment:
      GF_SECURITY_ADMIN_PASSWORD: password
      GF_USERS_ALLOW_SIGN_UP: 0
      GF_SMTP_ENABLED: 0
    volumes:
      - grafanadata:/var/lib/grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - prometheus

volumes:
  prometheusdata:
    driver: local
  grafanadata:
    driver: local

networks:
  prometheus:
    driver: bridge