version: '3.2'

services:
  blackbox-exporter:
    image: prom/blackbox-exporter:${BLACKBOX_EXPORTER_VERSION-latest}
    volumes:
      - $PWD/config/blackbox.yml:/etc/blackbox_exporter/blackbox.yml
    command:
      - '--config.file=/etc/blackbox_exporter/blackbox.yml'
      - '--history.limit=0'
    ports:
      - 9115:9115
    dns:
      - 1.1.1.1
      - 1.0.0.1
      - 8.8.8.8
      - 8.8.4.4
      - 208.67.222.222
      - 208.67.220.220
    restart: unless-stopped
    networks:
      - exporters

networks:
  exporters:
    driver: bridge