version: '3.2'

services:
  prometheus:
    image: prom/prometheus:v${PROMETHEUS_VERSION}
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/alert.rules.yml://etc/prometheus/alert.rules.yml
      - ./prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.route-prefix=/'
      - '--storage.tsdb.retention.time=${PROMETHEUS_RETENTION}'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    restart: always
    networks:
      - prometheus

  alertmanager:
    image: prom/alertmanager:v${ALERTMANAGER_VERSION}
    volumes:
      - ./config/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    ports:
      - 9091:9091
    depends_on:
      - prometheus
    restart: always
    networks:
      - prometheus

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}
    volumes:
      - ./grafana/data:/var/lib/grafana
    ports:
      - 3000:3000
    links:
      - prometheus:prometheus
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - prometheus

networks:
  prometheus:
    driver: bridge