version: '3.2'

services:
  nginx:
    image: nginx:${NGINX_VERSION-1.20-alpine}
    volumes:
      - $PWD/templates:/etc/nginx/templates
    environment:
      - NGINX_HOST=${NGINX_HOST-example.com}
      - NGINX_PORT=${NGINX_PORT-80}
    ports:
      - 80:80
    restart: always
    networks:
      - proxys

networks:
  proxys:
    driver: bridge