version: '3.2'

services:
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-${ZABBIX_VERSION-5.4}-latest
    depends_on:
      - zabbix-database
    links:
      - zabbix-database
    environment:
      - DB_SERVER_HOST=zabbix-database
      - DB_SERVER_PORT=5432
      - POSTGRES_USER=${ZABBIX_DB_USER-zabbix-user}
      - POSTGRES_PASSWORD=${ZABBIX_DB_PASSWORD-zabbix-password}
      - POSTGRES_DB=${ZABBIX_DB_DB-zabbix}
    ports:
      - 10050:10050
    restart: unless-stopped
    networks:
      - zabbix

  zabbix-frontend:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-${ZABBIX_VERSION-5.4}-latest
    depends_on:
      - zabbix-server
    links:
      - zabbix-database
      - zabbix-server
    environment:
      - DB_SERVER_HOST=zabbix-database
      - POSTGRES_USER=${ZABBIX_DB_USER-zabbix-user}
      - POSTGRES_PASSWORD=${ZABBIX_DB_PASSWORD-zabbix-password}
      - POSTGRES_DB=${ZABBIX_DB_DB-zabbix}
      - ZBX_SERVER_HOST=zabbix-server
      - TZ=${ZABBIX_TIMEZONE-Europe/Bucharest}
    ports:
      - 80:8080
      - 443:8443
    restart: unless-stopped
    networks:
      - zabbix

  zabbix-database:
    image: postgres:${PGSQL_VERSION-14}-alpine
    volumes:
      - pgsqldata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${ZABBIX_DB_USER-zabbix-user}
      - POSTGRES_PASSWORD=${ZABBIX_DB_PASSWORD-zabbix-password}
      - POSTGRES_DB=${ZABBIX_DB_DB-zabbix}
    restart: unless-stopped
    networks:
      - zabbix

volumes:
  pgsqldata:
    driver: local

networks:
  zabbix:
    driver: bridge