version: '3.2'

services:
  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:${ROCKETCHAT_VERSION-5.0.3}
    restart: on-failure
    environment:
      MONGO_URL: "${MONGO_URL\
        -mongodb://${MONGODB_ADVERTISED_HOSTNAME-mongodb}:${MONGODB_INITIAL_PRIMARY_PORT_NUMBER-27017}/\
        ${MONGODB_DATABASE-rocketchat}?replicaSet=${MONGODB_REPLICA_SET_NAME-rs0}}"
      MONGO_OPLOG_URL: "${MONGO_OPLOG_URL\
        -mongodb://${MONGODB_ADVERTISED_HOSTNAME-mongodb}:${MONGODB_INITIAL_PRIMARY_PORT_NUMBER-27017}/\
        local?replicaSet=${MONGODB_REPLICA_SET_NAME-rs0}}"
      ROOT_URL: ${ROOT_URL-http://localhost:3000}
      PORT: 3000
      DEPLOY_METHOD: docker
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    networks:
      - rocketchat

  mongodb:
    image: docker.io/bitnami/mongodb:${MONGODB_VERSION-5.0}
    restart: unless-stopped
    volumes:
      - $PWD/mongodb-data:/bitnami/mongodb
      - $PWD/mongodb-backup:/mongodb-backup
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: ${MONGODB_REPLICA_SET_NAME-rs0}
      MONGODB_PORT_NUMBER: ${MONGODB_PORT_NUMBER-27017}
      MONGODB_INITIAL_PRIMARY_HOST: ${MONGODB_INITIAL_PRIMARY_HOST-mongodb}
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: ${MONGODB_INITIAL_PRIMARY_PORT_NUMBER-27017}
      MONGODB_ADVERTISED_HOSTNAME: ${MONGODB_ADVERTISED_HOSTNAME-mongodb}
      MONGODB_ENABLE_JOURNAL: ${MONGODB_ENABLE_JOURNAL-true}
      ALLOW_EMPTY_PASSWORD: ${ALLOW_EMPTY_PASSWORD-yes}
    networks:
      - rocketchat

networks:
  rocketchat:
    driver: bridge