version: '3.2'

services:
  mysql:
    image: mysql:${MYSQL_VERSION-8}
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD-rootpassword}
      MYSQL_USER: ${MYSQL_USERNAME-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD-password}
      MYSQL_DATABASE: ${MYSQL_DB_NAME-database}
    ports:
      - 3306:3306
    restart: unless-stopped
    networks:
      - databases

volumes:
  mysqldata:
    driver: local

networks:
  databases:
    driver: bridge