version: '3.2'

services:
  postgresql:
    image: postgres:${PGSQL_VERSION-14}-alpine
    volumes:
      - pgsqldata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${PGSQL_USER-user}
      - POSTGRES_PASSWORD=${PGSQL_PASSWORD-password}
      - POSTGRES_DB=${PGSQL_NAME-database}
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - databases

volumes:
  pgsqldata:
    driver: local

networks:
  databases:
    driver: bridge