version: '3.2'

services:
  postgresql:
    image: postgres:${PGSQL_VERSION-14}-alpine
    volumes:
      - pgsqldata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${PGSQL_USERNAME-user}
      - POSTGRES_PASSWORD=${PGSQL_PASSWORD-password}
      - POSTGRES_DB=${PGSQL_DB_NAME-database}
    ports:
      - 5432:5432
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGSQL_PASSWORD-password}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - databases

volumes:
  pgsqldata:
    driver: local

networks:
  databases:
    driver: bridge